CREATE TABLE IF NOT EXISTS USER (
  id     VARCHAR(255) PRIMARY KEY,
  name   VARCHAR(255) NOT NULL,
  age    INT,
  mobile VARCHAR(255),
  UNIQUE KEY (name)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS MI_BLOG (
  id      VARCHAR(255) PRIMARY KEY,
  title   VARCHAR(255),
  content VARCHAR(255),
  userId  VARCHAR(255)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
